const sliders=['europa-slider','asia-slider','america-slider','africa-slider'];
sliders.forEach(slider=>{new Swiper(`.${slider}`,{slidesPerView:1,spaceBetween:10,loop:true,navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev'},breakpoints:{600:{slidesPerView:2},900:{slidesPerView:3}}});});
const translations={es:{welcome:"Bienvenido a Luxury Brizon Travels",subtitle:"Experiencias de lujo y exclusividad nunca antes vistas",discover:"Descubre nuestros viajes"},en:{welcome:"Welcome to Luxury Brizon Travels",subtitle:"Luxury and exclusive experiences like never before",discover:"Discover our trips"},fr:{welcome:"Bienvenue à Luxury Brizon Travels",subtitle:"Des expériences de luxe et exclusives jamais vues auparavant",discover:"Découvrez nos voyages"},de:{welcome:"Willkommen bei Luxury Brizon Travels",subtitle:"Luxus- und exklusive Erlebnisse wie nie zuvor",discover:"Entdecken Sie unsere Reisen"}};
function setLanguage(lang){document.querySelector('.hero-title').innerText=translations[lang].welcome;document.querySelector('.hero-subtitle').innerText=translations[lang].subtitle;document.querySelector('.btn').innerText=translations[lang].discover;}
const userLang=navigator.language.slice(0,2);setLanguage(translations[userLang]?userLang:'es');
document.querySelectorAll('.language-selector button').forEach(btn=>{btn.addEventListener('click',e=>{setLanguage(e.target.dataset.lang);});});
let cart=[];document.querySelectorAll('.add-to-cart').forEach(btn=>{btn.addEventListener('click',e=>{const card=e.target.closest('.card');const title=card.querySelector('h3').innerText;const price=card.querySelector('.price').innerText;cart.push({title,price});renderCart();e.target.innerText="Agregado";setTimeout(()=>e.target.innerText="Reservar",1000);});});
function renderCart(){const cartDiv=document.getElementById('cart');if(cart.length===0){cartDiv.innerHTML='<p>El carrito está vacío</p>';return;}cartDiv.innerHTML=cart.map(item=>`<p>${item.title} - ${item.price}</p>`).join('')+`<p><strong>Total: ${cart.reduce((sum,i)=>sum+parseInt(i.price.replace('€','')),0)} €</strong></p>`;}
document.getElementById('contact-form').addEventListener('submit',e=>{e.preventDefault();const name=e.target.name.value;const email=e.target.email.value;const phone=e.target.phone.value;const message=e.target.message.value;alert(`Gracias ${name}, hemos recibido tu solicitud. Te contactaremos pronto.`);console.log({name,email,phone,message,cart});e.target.reset();});
paypal.Buttons({createOrder:function(data,actions){const total=cart.reduce((sum,i)=>sum+parseInt(i.price.replace('€','')),0);return actions.order.create({purchase_units:[{amount:{value:total}}]});},onApprove:function(data,actions){return actions.order.capture().then(function(details){alert('Pago completado. Gracias '+details.payer.name.given_name);cart=[];renderCart();});}}).render('#paypal-button-container');
